database:
  type: "postgres"  # Options: mariadb, oracle, postgres, mssql

  mariadb:
    host: "localhost"
    port: 3306
    user: "user"
    password: "pass"
    database: "adif_logs"

  oracle:
    host: "localhost"
    port: 1521
    user: "user"
    password: "pass"
    service_name: "orcl"

  postgres:
    host: "localhost"
    port: 5432
    user: "user"
    password: "pass"
    database: "adif_logs"

  mssql:
    host: "localhost"
    port: 1433
    user: "user"
    password: "pass"
    database: "adif_logs"
